### ISSUE TITLE
Tsuquyomi hijacks Ctrl-6 shortcut

### ISSUE THREAD

**Issue by bodograumann** [Quramy/tsuquyomi#249]
I use the shortcut Ctrl-6 quite often for switching back and forth between buffers and it seems tha Tsuquyomi is messing with it. I tried to see if it is mapped, but couldn‘t find anything about that. There is no information about it in the Readme, vim help and when I call `:nmap` it seems the first lines are cut off. This it what I seem, followed by other unrelated bindings

```
   <C-T>        @<Plug>(TsuquyomiGoBack)
   <C-W><C-]>   @<Plug>(TsuquyomiSplitDefinition)
   <C-W>]       @<Plug>(TsuquyomiSplitDefinition)
   <C-]>        @<Plug>(TsuquyomiDefinition)
   <C-^>        @<Plug>(TsuquyomiReferences)
n  y<C-G>      &@:<C-U>call setreg(v:register, fugitive#Object(@%))<CR>
   <Plug>(TsuquyomiRenameSymbolCS) *@:TsuquyomiRenameSymbolCS <CR>
   <Plug>(TsuquyomiRenameSymbolS) *@:TsuquyomiRenameSymbolS <CR>
   <Plug>(TsuquyomiImport) *@:TsuquyomiImport <CR>
   <Plug>(TsuquyomiSignatureHelp) *@:TsuquyomiSignatureHelp <CR>
   <Plug>(TsuquyomiQuickFix) *@:TsuquyomiQuickFix <CR>
   <Plug>(TsuquyomiRenameSymbolC) *@:TsuquyomiRenameSymbolC <CR>
   <Plug>(TsuquyomiRenameSymbol) *@:TsuquyomiRenameSymbol <CR>
   <Plug>(TsuquyomiReferences) *@:TsuquyomiReferences <CR>
   <Plug>(TsuquyomiImplementation) *@:TsuquyomiImplementation <CR>
   <Plug>(TsuquyomiGoBack) *@:TsuquyomiGoBack <CR>
   <Plug>(TsuquyomiTypeDefinition) *@:TsuquyomiTypeDefinition <CR>
   <Plug>(TsuquyomiSplitDefinition) *@:TsuquyomiSplitDefinition <CR>
   <Plug>(TsuquyomiDefinition) *@:TsuquyomiDefinition <CR>
[…]
```

**Comment by nickspoons** [comment]
`<C-6>` is the same as `<C-^>` in vim. tsuquyomi maps `<C-^>` to `<Plug>(TsuquyomiReferences)` unless either:
1. You add `let g:tsuquyomi_disable_default_mappings = 1` to your .vimrc
2. You map something else to `<Plug>(TsuquyomiReferences)`, e.g.
   ```vim
   nmap <buffer> <Space><C-]> <Plug>(TsuquyomiReferences)
   ```

I quite like that 2nd option, where `<C-]>` is for going to definition and `<Space><C-]>` is for finding references

**Comment by bodograumann** [comment]
I understand and would like to employ the second option. As I am not using the us layout, I have tried the following:

    nnoremap <leader>ref <Plug>(TsuquyomiReferences)

Unfortunately when I try to use the mapping, nothing happens.

**Comment by tyler-reitz** [comment]
Is there a quick easy to way to disable a single tsuquyomi mapping? I've spent the last hour trying to override the `<C-^>` mapping but haven't been able to since it's done via autoloading. Simply re-mapping in the after directory does not work. It would be nice if the option to re-map/disable individual mappings were provided as it's overriding a common vim built-in mapping.

**Comment by nickspoons** [comment]
@tyler-reitz option 2 in my previous comment shows how to override that single mapping

**Comment by nickspoons** [comment]
@bodograumann for a mapping to a `<Plug>` mapping, you can't use `nnoremap` - it _is_ a recursive mapping. So use this:

    nmap <leader>ref <Plug>(TsuquyomiReferences)

**Comment by tyler-reitz** [comment]
I tried that, first placing the remapping in my `.vimrc`. That didn't work so I tried making an `after/tsuquyomi` directory and remapping there and no dice either. I'm an intermediate-ish vim user on a good day so I admit that there may be something I'm unaware of.

**Comment by nickspoons** [comment]
It should be in your .vimrc, or possibly `~/.vim/ftplugin/typescript.vim` ( _not_ `~/.vim/after/ftplugin/typescript.vim`). The point is for the mapping to exist before tsuquyomi hits [this line](https://github.com/Quramy/tsuquyomi/blob/fd47e1ac75ee3a09e13a3b7a8f609907c2b6b542/autoload/tsuquyomi/config.vim#L256) so start off with it in your .vimrc which is sourced before all other scripts.

However if this is fine in your .vimrc, drop the `<buffer>`, otherwise the mapping will only apply to the initial buffer vim loads and all subsequent .ts buffers won't have it.

    nmap <Space><C-]> <Plug>(TsuquyomiReferences)

**Comment by tyler-reitz** [comment]
Ah, the `<buffer>` in the`.vimrc` was the issue. Thanks for the help :+1:

**Comment by bodograumann** [comment]
Thanks @nickspoons , that was my mistake indeed :-)

**Comment by vitaly-zdanevich** [comment]
After installing of this plugin I found that my my Ctrl-6 to go to the previous buffer is not works anymore - looks like bad default mapping.
