### ISSUE TITLE
TsuImport not working for me?

### ISSUE THREAD

**Issue by rajinder-yadav** [Quramy/tsuquyomi#96]
When I type TsuImport I am greeted with this following message:
```
[Tsuqutomi] You can import from 2 more than modules. Select one:
```

I am coding a Angular 2 app and this occurs when I place the cursor over the directive `@Component`. I am not sure what I am suppose to select, no options is presented?

```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Router Example';
}
```

**Comment by rajinder-yadav** [comment]
Also if I hit Enter I see the following 2 errors:
```
[Tsuqutomi] Invalid module path.
[Tsuqutomi] No search result.
```

**Comment by bdauria** [comment]
You can circle through the choices using the Tab key.

**Comment by rajinder-yadav** [comment]
@bdauria Thanks, this worked for me. Question before I close this off, I seem to get an import that looks like this:
```
import { Component } from "@angular/core/src/metadata/directives";
```
Is there a way to make this just:
```
import { Component } from "@angular/core";
```

**Comment by Quramy** [comment]
@rajinder-yadav 

Now TsuImport cannot complete `import { Component } from "@angular/core";` because the following limitation:

### copied from README

This command has the following limitation:

* This command searches aliases from only files already opened or referenced
* This command searches aliases which are exported explicitly.

In other words, if your project has the following 2 files, `import { foo } from './lib';` is a valid declaration, but Tsuquyomi can create only `import { foo } from './lib/foo';`.

```ts
/* lib/index.ts */
export * from './foo';
```

```ts
/* lib/foo.ts */
export const foo = 'FOO'
```

**Comment by rajinder-yadav** [comment]
Thanks again everyone, it's a simple edit to get the path I know I need 👍
Works for me!
